site_name: terraform-gitlab-repository Documentation
theme: 'material'
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - smarty
  - wikilinks
  - codehilite:
      linenums: True
extra:
  palette:
    primary: '#087da1'
    accent: '#00a889'
  font:
    text: 'Source Sans Pro'

repo_name: 'hadenlabs/terraform-gitlab-repository'
repo_url: 'https://github.com/hadenlabs/terraform-gitlab-repository'

google_analytics:
  - ''
  - 'auto'
